language: php
dist: "trusty"
php:
    - "7.2"

before_script:
    - sudo apt-get update
    - sudo apt-get install build-essential libpq-dev libssl-dev openssl libffi-dev zlib1g-dev
    - sudo apt-get install python3-pip python3-dev
    - sudo apt-get install python3.7
    - sudo apt-get install apache2 libapache2-mod-fastcgi
    # enable php-fpm
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
    - sudo chown -R travis:travis /var/lib/apache2/fastcgi
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    # configure apache virtual hosts
    - sudo cp -f tests/.config/apache.conf /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    - sudo service apache2 restart
    # install python dependencies
    - python3 -V
    - sudo pip3 install --upgrade colorama requests
    # execute custom script
    - sudo chmod ugo+x tests/config.sh
    - ./tests/config.sh --copy

script:
    - python3 tests/apiTest.py

after_script:
    - ./tests/config.sh --restore